version: "3"

services:
  stock_scraping_api:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfileのパス
    image: stock_scraping_api_image # イメージ名を指定
    platform: linux/x86_64
    container_name: stock_scraping_api_container # コンテナ名
    environment: # Cloud Run上で動かすときに不要な環境変数はここで定義する
      GOOGLE_APPLICATION_CREDENTIALS: /app/sa.json
      ENVIRONMENT: local
    ports:
      - "8000:8000" # ホストの8080ポートをコンテナの8000ポートにマッピング
    volumes:
      - ./:/app # ホストのディレクトリをコンテナにマウント
